name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/mattfoster/sectools/sectools
    - name: Login to the Docker registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - name: Push container to the repo
      run: docker push drmpf/sectools
